---
- name: Setup Workers Kube directory
  ansible.builtin.file:
    path: "/home/{{ kubernetes_user }}/.kube"
    state: directory
    owner: "{{ kubernetes_user }}"
    group: "{{ kubernetes_user }}"
    mode: '0755'

- name: Copy kube config file to remote
  run_once: true
  ansible.builtin.copy:
    src: "{{ kubernetes_kube_config_location }}"
    dest: "/home/{{ kubernetes_user }}/.kube/config"
    owner: "{{ kubernetes_user }}"
    group: "{{ kubernetes_user }}"
    mode: '0755'

- name: Copy join script to remote
  run_once: true
  ansible.builtin.copy:
    src: "{{ kubernetes_join_script }}"
    dest: "/home/{{ kubernetes_user }}/kubeadm-join.sh"
    owner: "{{ kubernetes_user }}"
    group: "{{ kubernetes_user }}"
    mode: '0755'

- name: Execute kubeadm-join.sh
  ansible.builtin.shell: "/home/{{ kubernetes_user }}/kubeadm-join.sh"
  become: true
  when: "'kube_workers' in group_names"

